/**
 * Equipment Icons - maps subtype codes to random sprite paths.
 * Auto-generated from shared/public/assets/equipments/
 */

/** Asset folder path (relative to public root) for each icon set. */
const ICON_PATHS: Record<string, string> = {
  swords: "/assets/equipments/weapon/swords",
  axes: "/assets/equipments/weapon/axes",
  blades: "/assets/equipments/weapon/blades",
  scrolls: "/assets/equipments/weapon/scrolls",
  bows: "/assets/equipments/weapon/bows",
  staffs: "/assets/equipments/weapon/staffs",
  helmets: "/assets/equipments/armor/helmets",
  plates: "/assets/equipments/armor/plates",
  mantles: "/assets/equipments/armor/mantles",
  gloves: "/assets/equipments/armor/gloves",
  belts: "/assets/equipments/armor/belts",
  boots: "/assets/equipments/boots/boots",
  rings: "/assets/equipments/accessory/rings",
  amulets: "/assets/equipments/accessory/amulets",
};

/** Maps subtype code to icon set key. */
const SUBTYPE_ICON_SET: Record<string, string> = {
  oh_sword: "swords",
  oh_axe: "axes",
  oh_dagger: "blades",
  oh_wand: "scrolls",
  oh_mace: "axes",
  th_sword: "swords",
  th_axe: "axes",
  th_bow: "bows",
  th_staff: "staffs",
  th_mace: "axes",
  helm_heavy: "helmets",
  helm_light: "helmets",
  helm_circlet: "helmets",
  amu_pendant: "amulets",
  amu_talisman: "amulets",
  amu_locket: "amulets",
  arm_plate: "plates",
  arm_leather: "mantles",
  arm_robe: "mantles",
  arm_chain: "mantles",
  ring_ruby: "rings",
  ring_sapphire: "rings",
  ring_topaz: "rings",
  ring_gold: "rings",
  ring_iron: "rings",
  glov_gauntlet: "gloves",
  glov_bracer: "gloves",
  glov_wrap: "gloves",
  belt_leather: "belts",
  belt_chain: "belts",
  belt_heavy: "belts",
  belt_cloth: "belts",
  boot_plate: "boots",
  boot_leather: "boots",
  boot_silk: "boots",
  boot_chain: "boots",
};

/** Icon filenames per set. */
const ICON_FILES: Record<string, string[]> = {
  swords: [
    "Ancient_Bloodthorn_Cleaver.png",
    "Ancient_Duskbane_Longsword.png",
    "Ancient_Thornspire_Cleaver.png",
    "Ashborn_Cleaver.png",
    "Ashborn_Katana.png",
    "Ashbringer's_Edge.png",
    "Ashcrown_Falchion.png",
    "Ashenbrand_Cleaver.png",
    "Ashenfang_Cleaver.png",
    "Azureblight_Cleaver.png",
    "Bloodoak_Cleaver.png",
    "Bloodpact_Cleaver.png",
    "Bloodrusted_Cleaver.png",
    "Bloodrust_Cleaver.png",
    "Bloodthorn_Cleaver.png",
    "Bloodveil_Cleaver.png",
    "Bloodworn_Cleaver.png",
    "Bonefang_Cleaver.png",
    "Bonewraith_Cleaver.png",
    "Cerulean_Fang.png",
    "Cursed_Azureblight_Cleaver.png",
    "Cursed_Bloodrust_Cleaver.png",
    "Cursed_Duskfang_Cleaver.png",
    "Cursed_Glacial_Fang_Blade.png",
    "Cursed_Thornspire_Cleaver.png",
    "Dawnblight_Cleaver.png",
    "Dawnbringer's_Edge.png",
    "Dawnpiercer_Blade.png",
    "Duskbane_Cleaver.png",
    "Duskbane_Longsword.png",
    "Duskblight_Cleaver.png",
    "Duskbrand_Cleaver.png",
    "Duskbringer's_Edge.png",
    "Duskfall_Cleaver.png",
    "Duskfang_Cleaver.png",
    "Emberbrand_Cleaver.png",
    "Embercinder_Cleaver.png",
    "Emberclaw_Reaver.png",
    "Embercleaver_Sabre.png",
    "Emberfang_Cleaver.png",
    "Emberhusk_Cleaver.png",
    "Ember_Azureblight_Cleaver.png",
    "Ember_Emberfang_Cleaver.png",
    "Ember_Thornspire_Cleaver.png",
    "Forsaken_Bloodthorn_Cleaver.png",
    "Forsaken_Bonewraith_Cleaver.png",
    "Forsaken_Embercinder_Cleaver.png",
    "Frostbane_Cleaver.png",
    "Frostbind_Cleaver.png",
    "Frostbite_Cleaver.png",
    "Frostpiercer's_Edge.png",
    "Gilded_Sunburst_Blade.png",
    "Glacial_Cleaver.png",
    "Glacial_Fang_Blade.png",
    "Goldflare_Cleaver.png",
    "Hollow_Emberfang_Cleaver.png",
    "Hollow_Emberfang_Cleaver_2.png",
    "Hollow_Emberfang_Cleaver_3.png",
    "Luminous_Cleaver.png",
    "Nightpiercer_Falchion.png",
    "Nightpurge_Cleaver.png",
    "Obsidian_Reaper.png",
    "Obsidian_Requiem.png",
    "Shadowblight_Cleaver.png",
    "Shadowfang_Cleaver.png",
    "Shadowrend_Cleaver.png",
    "Shattered_Ashenbrand_Cleaver.png",
    "Shattered_Ashenbrand_Cleaver_2.png",
    "Shattered_Duskbrand_Cleaver.png",
    "Shattered_Emberfang_Cleaver.png",
    "Shattered_Emberfang_Cleaver_2.png",
    "Shattered_Thornspire_Cleaver.png",
    "Storm_Ashenbrand_Cleaver.png",
    "Storm_Azureblight_Cleaver.png",
    "Storm_Azureblight_Cleaver_2.png",
    "Storm_Duskbane_Longsword.png",
    "Storm_Duskfang_Cleaver.png",
    "Storm_Glacial_Fang_Blade.png",
    "Thornshadow_Cleaver.png",
    "Thornspike_Cleaver.png",
    "Thornspire_Cleaver.png",
    "Thornspire_Reaver.png",
    "Thornwood_Cleaver.png",
    "Tideborne_Cleaver.png",
    "Umbral_Cleaver.png",
    "Umbral_Reaper.png",
    "Veilpiercer's_Bane.png",
    "Veilpiercer's_Edge.png",
    "Veilpiercer_Blade.png",
    "Veilpiercer_Halberd.png",
    "Verdantblight_Cleaver.png",
    "Verdant_Reaper's_Edge.png",
    "Verdant_Reaper.png",
    "Verdant_Reaver.png",
    "Violetscourge_Blade.png",
    "Voidborn_Duskbane_Cleaver.png",
    "Voidborn_Duskbane_Cleaver_2.png",
    "Voidborn_Duskbane_Cleaver_3.png",
    "Voidborn_Emberbrand_Cleaver.png",
    "Voidborn_Embercinder_Cleaver.png",
  ],
  axes: [
    "Amethyst_Rend.png",
    "Ancient_Bloodmoon_Cleaver.png",
    "Ancient_Bloodmoon_Cleaver_2.png",
    "Ashrender's_Cleaver.png",
    "Azureblight_Cleaver.png",
    "Blackened_Reaper's_Maul.png",
    "Blackpeak_Cleaver.png",
    "Blackpine_Reaper.png",
    "Blackreap_Cleaver.png",
    "Blackspine_Cleaver.png",
    "Blackthorn_Cleaver.png",
    "Blackthorn_Reaper.png",
    "Blight_Reaper.png",
    "Bloodaxe_of_the_Forsaken.png",
    "Bloodaxe_of_the_Hollow.png",
    "Bloodfall_Cleaver.png",
    "Bloodfang_Cleaver.png",
    "Bloodfell_Cleaver.png",
    "Bloodhewn_Maul.png",
    "Bloodletting_Reaper.png",
    "Bloodmoon_Cleaver.png",
    "Bloodmoon_Reaper.png",
    "Bloodmoon_Reaver.png",
    "Bloodmoss_Cleaver.png",
    "Bloodpact_Cleaver.png",
    "Bloodpeak_Cleaver.png",
    "Bloodpeak_Reaper.png",
    "Bloodreaper's_Cleave.png",
    "Bloodreaper's_Cleaver.png",
    "Bloodreaper's_Maul.png",
    "Bloodreaver's_Cleave.png",
    "Bloodreaver's_Maul.png",
    "Bloodrite_Cleaver.png",
    "Bloodrusted_Cleaver.png",
    "Bloodrust_Cleaver.png",
    "Bloodthorn_Cleaver.png",
    "Bloodthorn_Reaper.png",
    "Bonegrinder's_Cleave.png",
    "Bonegrinder's_Maul.png",
    "Cursed_Bloodmoon_Cleaver.png",
    "Cursed_Bloodmoon_Cleaver_2.png",
    "Cursed_Bloodpact_Cleaver.png",
    "Cursed_Bloodrust_Cleaver.png",
    "Duskfang_Maul.png",
    "Emberfang_Cleaver.png",
    "Emberfell_Cleaver.png",
    "Ember_Blackpeak_Cleaver.png",
    "Ember_Bloodmoon_Cleaver.png",
    "Ember_Bloodmoon_Cleaver_2.png",
    "Ember_Bloodmoon_Cleaver_3.png",
    "Ember_Bloodreaper's_Maul.png",
    "Ember_Bloodrite_Cleaver.png",
    "Forsaken_Bloodmoon_Cleaver.png",
    "Forsaken_Bloodmoon_Cleaver_2.png",
    "Forsaken_Bloodmoss_Cleaver.png",
    "Forsaken_Bloodreaper's_Cleave.png",
    "Forsaken_Bloodrite_Cleaver.png",
    "Forsaken_Ironpeak_Cleaver.png",
    "Frostbite_Cleaver.png",
    "Frostbite_Reaper.png",
    "Goldrim_Cleaver.png",
    "Goldrot_Cleaver.png",
    "Goldrot_Executioner.png",
    "Grimaxe_of_the_Void.png",
    "Grimstone_Reaper.png",
    "Grimwood_Cleaver.png",
    "Hollow_Bloodmoon_Cleaver.png",
    "Hollow_Bloodmoon_Cleaver_2.png",
    "Hollow_Bloodmoon_Cleaver_3.png",
    "Hollow_Bloodmoon_Cleaver_4.png",
    "Hollow_Bloodmoon_Cleaver_5.png",
    "Hollow_Bloodmoon_Cleaver_6.png",
    "Hollow_Bloodrite_Cleaver.png",
    "Ironpeak_Cleaver.png",
    "Ironwood_Cleaver.png",
    "Mournblight_Cleaver.png",
    "Ravencrest_Cleaver.png",
    "Ravenmaw_Cleaver.png",
    "Shadowrend_Hatchet.png",
    "Shattered_Blackspine_Cleaver.png",
    "Shattered_Bloodmoon_Cleaver.png",
    "Shattered_Bloodpeak_Cleaver.png",
    "Shattered_Bloodreaper's_Cleave.png",
    "Shattered_Emberfang_Cleaver.png",
    "Stormbreaker's_Maul.png",
    "Storm_Blackthorn_Cleaver.png",
    "Storm_Bloodmoon_Cleaver.png",
    "Storm_Bloodmoon_Cleaver_2.png",
    "Storm_Bloodrite_Cleaver.png",
    "Storm_Bloodrite_Cleaver_2.png",
    "Thornblight_Cleaver.png",
    "Tidebreaker's_Cleave.png",
    "Voidborn_Bloodmoon_Cleaver.png",
    "Voidborn_Bloodmoon_Cleaver_2.png",
    "Voidborn_Bloodmoon_Cleaver_3.png",
    "Voidborn_Bloodpact_Cleaver.png",
    "Voidborn_Bloodrust_Cleaver.png",
    "Voidborn_Ironpeak_Cleaver.png",
    "Voidreaper's_Maul.png",
    "Void_Splitter.png",
  ],
  blades: [
    "Amethyst_Blight.png",
    "Amethyst_Fang.png",
    "Amethyst_Nightbane.png",
    "Amethyst_Reaper's_Edge.png",
    "Ashblight_Dirk.png",
    "Azurebane_Katana.png",
    "Azureblight_Dirk.png",
    "Azureblight_Katana.png",
    "Azurebrand_Katana.png",
    "Bloodhunter's_Edge.png",
    "Bloodpact_Cleaver.png",
    "Bloodpetal_Cleaver.png",
    "Bloodthorn_Cleaver.png",
    "Bloodthorn_Crescent.png",
    "Bloodthorn_Dirk.png",
    "Bloodthorn_Falchion.png",
    "Bloodthorn_Katana.png",
    "Bloodthorn_Machete.png",
    "Bloodthorn_Talon.png",
    "Bloodvein_Cleaver.png",
    "Bonewood_Cleaver.png",
    "Corrosion's_Fang.png",
    "Crescent_Fang.png",
    "Crimson_Blight_Cleaver.png",
    "Crimson_Fang_Cleaver.png",
    "Crimson_Marrow_Blade.png",
    "Crimson_Marrow_Cleaver.png",
    "Crimson_Plume_Katana.png",
    "Crimson_Reaper's_Edge.png",
    "Crimson_Spine_Cleaver.png",
    "Crimson_Talon_Blade.png",
    "Crimson_Talon_Katana.png",
    "Crimson_Thorn_Blade.png",
    "Crimson_Thorn_Katana.png",
    "Duskblight_Cleaver.png",
    "Duskblight_Katana.png",
    "Duskfall_Cleaver.png",
    "Duskfang_Cleaver.png",
    "Duskpetal_Cleaver.png",
    "Dustbringer's_Edge.png",
    "Embercinder_Katana.png",
    "Emberfall_Cleaver.png",
    "Emberfang_Cleaver.png",
    "Emberheart_Katana.png",
    "Emberscourge_Cleaver.png",
    "Emberwright_Cleaver.png",
    "Ember_Nightfall_Cleaver.png",
    "Forsaken_Bloodthorn_Katana.png",
    "Forsaken_Crimson_Fang_Cleaver.png",
    "Forsaken_Nightfall_Cleaver.png",
    "Frostbrand_Katana.png",
    "Goldspine_Cleaver.png",
    "Hollow_Amethyst_Blight.png",
    "Hollow_Bloodthorn_Cleaver.png",
    "Hollow_Bloodthorn_Katana.png",
    "Hollow_Crimson_Blight_Cleaver.png",
    "Hollow_Nightfall_Cleaver.png",
    "Hollow_Talon.png",
    "Moonfall_Scimitar.png",
    "Nightfall_Cleaver.png",
    "Nightfall_Fang.png",
    "Nightfall_Katana.png",
    "Nightfang_Cleaver.png",
    "Nightfang_Crescent.png",
    "Nightpiercer's_Fang.png",
    "Nightpiercer_Katana.png",
    "Nightpurple_Cleaver.png",
    "Nightveil_Cleaver.png",
    "Nightveil_Fang.png",
    "Pestilence_Fang.png",
    "Ravenclaw_Cleaver.png",
    "Rotbone_Cleaver.png",
    "Rustbone_Cleaver.png",
    "Rusted_Fang_Katana.png",
    "Serpent's_Fang_Katana.png",
    "Serpentfall_Cleaver.png",
    "Serpentine_Fang.png",
    "Shattered_Amethyst_Blight.png",
    "Shattered_Bloodthorn_Cleaver.png",
    "Shattered_Bloodthorn_Cleaver_2.png",
    "Skyrender_Katana.png",
    "Stormrend_Katana.png",
    "Storm_Amethyst_Fang.png",
    "Storm_Bloodthorn_Cleaver.png",
    "Storm_Bloodthorn_Cleaver_2.png",
    "Storm_Bloodthorn_Crescent.png",
    "Thornleaf_Cleaver.png",
    "Thornspire_Dirk.png",
    "Thornspire_Halberd.png",
    "Thornspire_Katana.png",
    "Twilight_Severance.png",
    "Veilpiercer_Katana.png",
    "Verdant_Fang_Cleaver.png",
    "Verdant_Reaper.png",
    "Verdant_Scourge.png",
    "Verdant_Spine.png",
    "Vilethorn_Cleaver.png",
    "Voidborn_Duskblight_Katana.png",
    "Voidfeather_Katana.png",
    "Void_Reaper's_Edge.png",
  ],
  scrolls: [
    "Abyssal_Codex_Scroll.png",
    "Amethyst_Covenant_Scroll.png",
    "Ancient_Crimson_Covenant_Scroll.png",
    "Ancient_Umbral_Codex.png",
    "Ancient_Veilbound_Codex.png",
    "Ancient_Veilbound_Codex_2.png",
    "Ancient_Veilscript_Codex.png",
    "Ancient_Verdant_Whisper_Scroll.png",
    "Arcaneblight_Codex.png",
    "Azurite_Codex_of_Ruin.png",
    "Azurite_Codex_of_Tides.png",
    "Bloodpact_Grimoire.png",
    "Cerulean_Codex_Scroll.png",
    "Chronofracture_Codex.png",
    "Chronometer_of_the_Forsaken.png",
    "Chronoveil_Manuscript.png",
    "Cinderpact_Grimoire.png",
    "Cobalt_Covenant_Scroll.png",
    "Codex_of_Fractured_Minds.png",
    "Codex_of_Smoldering_Ruin.png",
    "Codex_of_the_Void_Bound.png",
    "Codex_of_Unmaking.png",
    "Codex_of_Waning_Starlight.png",
    "Codex_of_Waning_Truths.png",
    "Codex_of_Wasting.png",
    "Codex_of_Whispered_Ruin.png",
    "Codex_of_Withering_Ruin.png",
    "Codex_of_Withering_Runes.png",
    "Codex_of_Withering_Truths.png",
    "Crimson_Binding_Scroll.png",
    "Crimson_Codex_of_Binding.png",
    "Crimson_Codex_of_Ruin.png",
    "Crimson_Codex_of_Unmaking.png",
    "Crimson_Codex_of_Withering.png",
    "Crimson_Covenant_Scroll.png",
    "Crimson_Doctrine_Scroll.png",
    "Crimson_Grimoire_of_Whispers.png",
    "Crimson_Oath_Scroll.png",
    "Crimson_Pact_Scroll.png",
    "Crimson_Theurgy_Scroll.png",
    "Cryptbound_Grimoire.png",
    "Cursed_Crimson_Covenant_Scroll.png",
    "Cursed_Grimveil_Codex.png",
    "Cursed_Veilbound_Grimoire.png",
    "Cursed_Veilbound_Grimoire_2.png",
    "Cursed_Veilbound_Grimoire_3.png",
    "Cursed_Veilscript_Codex.png",
    "Cursed_Veilweave_Codex.png",
    "Embercall_Grimoire.png",
    "Embercinder_Codex.png",
    "Embercrest_Codex.png",
    "Embercrypt_Codex.png",
    "Embercrypt_Grimoire.png",
    "Embercursed_Grimoire.png",
    "Emberspire_Codex.png",
    "Emberveil_Codex.png",
    "Emberwick_Codex.png",
    "Emberwraith_Codex.png",
    "Ember_Crimson_Codex_of_Unmaking.png",
    "Ember_Crimson_Covenant_Scroll.png",
    "Ember_Crimson_Covenant_Scroll_2.png",
    "Ember_Cryptbound_Grimoire.png",
    "Ember_Frostbind_Codex.png",
    "Ember_Umbral_Codex.png",
    "Ember_Veilbound_Grimoire.png",
    "Ember_Veilbound_Grimoire_2.png",
    "Ember_Veilrift_Codex.png",
    "Ember_Veilweave_Codex.png",
    "Ember_Verdant_Codex_of_Thorns.png",
    "Flameburst_Codex.png",
    "Forsaken_Codex_of_Withering_Truths.png",
    "Forsaken_Crimson_Covenant_Scroll.png",
    "Forsaken_Crimson_Covenant_Scroll_2.png",
    "Forsaken_Crimson_Covenant_Scroll_3.png",
    "Forsaken_Embercall_Grimoire.png",
    "Forsaken_Veilbound_Codex.png",
    "Forsaken_Veilbound_Codex_2.png",
    "Forsaken_Veilbound_Grimoire.png",
    "Forsaken_Veilwhisper_Codex.png",
    "Forsaken_Verdant_Codex_of_Thorns.png",
    "Frostbind_Codex.png",
    "Frostpact_Codex.png",
    "Frostweave_Codex.png",
    "Goldleaf_Incantation.png",
    "Grimoire_of_Ash_Ruin.png",
    "Grimoire_of_Cinders.png",
    "Grimoire_of_Ember_Runes.png",
    "Grimoire_of_Shattered_Seals.png",
    "Grimoire_of_Sundered_Seals.png",
    "Grimoire_of_Sundered_Thresholds.png",
    "Grimoire_of_Wailing_Ether.png",
    "Grimscroll_of_Withering.png",
    "Grimstone_Codex.png",
    "Grimtome_of_Withering.png",
    "Grimtongue_Codex.png",
    "Grimveil_Codex.png",
    "Hollow_Codex_of_Fractured_Minds.png",
    "Hollow_Codex_of_Withering_Truths.png",
    "Hollow_Umbral_Codex.png",
    "Hollow_Veilthread_Codex.png",
    "Hollow_Verdant_Grimoire.png",
    "Nightbound_Codex.png",
    "Ossuary_Grimoire.png",
    "Paw_of_the_Covenant.png",
    "Scepter_of_Dominion.png",
    "Scorched_Covenant_Scroll.png",
    "Scorched_Grimoire_of_Cinders.png",
    "Scorchveil_Codex.png",
    "Scrollbark_Grimoire.png",
    "Scrollbound_Anathema.png",
    "Scrolls_of_the_Starfall_Covenant.png",
    "Scrolls_of_the_Violet_Covenant.png",
    "Scroll_of_Aetheric_Unfolding.png",
    "Scroll_of_Fell_Incantations.png",
    "Scroll_of_Twilight_Ruin.png",
    "Scroll_of_Withering_Truths.png",
    "Serpent's_Covenant_Scroll.png",
    "Shadowrift_Codex.png",
    "Shadowveil_Grimoire.png",
    "Shattered_Codex_of_Withering_Truths.png",
    "Shattered_Embercall_Grimoire.png",
    "Shattered_Grimoire_of_Cinders.png",
    "Shattered_Veilbound_Grimoire.png",
    "Shattered_Veilbound_Grimoire_2.png",
    "Shattered_Veilbound_Grimoire_3.png",
    "Shattered_Veilrift_Codex.png",
    "Shattered_Verdant_Covenant_Scroll.png",
    "Smoldering_Grimoire.png",
    "Soulbound_Codex.png",
    "Starfall_Grimoire.png",
    "Stormbound_Codex.png",
    "Stormveil_Grimoire.png",
    "Storm_Codex_of_Fractured_Minds.png",
    "Storm_Codex_of_Withering_Truths.png",
    "Storm_Crimson_Covenant_Scroll.png",
    "Storm_Crimson_Covenant_Scroll_2.png",
    "Storm_Crimson_Covenant_Scroll_3.png",
    "Storm_Crimson_Pact_Scroll.png",
    "Storm_Scroll_of_Withering_Truths.png",
    "Storm_Veilbound_Codex.png",
    "Storm_Veilbound_Grimoire.png",
    "Storm_Veilscript_Codex.png",
    "Storm_Veilscript_Codex_2.png",
    "Storm_Verdant_Codex_of_Thorns.png",
    "Storm_Verdant_Codex_Scroll.png",
    "Storm_Verdant_Covenant_Scroll.png",
    "Teal_Covenant_Scroll.png",
    "Tidecaller's_Covenant.png",
    "Umbral_Codex.png",
    "Umbral_Codex_Scroll.png",
    "Veilbound_Codex.png",
    "Veilbound_Grimoire.png",
    "Veilcaster's_Codex.png",
    "Veilmark_Codex.png",
    "Veilmoon_Grimoire.png",
    "Veilpact_Grimoire.png",
    "Veilrift_Codex.png",
    "Veilscribe_Codex.png",
    "Veilscript_Codex.png",
    "Veilscript_Grimoire.png",
    "Veilstitched_Codex.png",
    "Veilthread_Codex.png",
    "Veilthrone_Grimoire.png",
    "Veilwarp_Codex.png",
    "Veilweaver's_Codex.png",
    "Veilweave_Codex.png",
    "Veilwhisper_Codex.png",
    "Veilwrought_Grimoire.png",
    "Verdant_Blight_Codex.png",
    "Verdant_Blight_Grimoire.png",
    "Verdant_Codex.png",
    "Verdant_Codex_of_Thorns.png",
    "Verdant_Codex_Scroll.png",
    "Verdant_Covenant_Scroll.png",
    "Verdant_Curse_Scroll.png",
    "Verdant_Decay_Scroll.png",
    "Verdant_Entropy_Scroll.png",
    "Verdant_Grimoire.png",
    "Verdant_Grimoire_of_Blight.png",
    "Verdant_Whisper_Scroll.png",
    "Violetpact_Grimoire.png",
    "Violet_Covenant_Scroll.png",
    "Violet_Runewhisper_Scroll.png",
    "Void-Sealed_Codex.png",
    "Voidborn_Abyssal_Codex_Scroll.png",
    "Voidborn_Abyssal_Codex_Scroll_2.png",
    "Voidborn_Codex_of_Withering_Truths.png",
    "Voidborn_Crimson_Covenant_Scroll.png",
    "Voidborn_Frostbind_Codex.png",
    "Voidborn_Veilbound_Codex.png",
    "Voidborn_Veilbound_Grimoire.png",
    "Voidborn_Veilbound_Grimoire_2.png",
    "Voidborn_Veilbound_Grimoire_3.png",
    "Voidmarks_Grimoire.png",
    "Voidpact_Grimoire.png",
    "Void_Compendium.png",
    "Void_Covenant_Scroll.png",
    "Void_Whisper_Codex.png",
    "Vortex_Codex.png",
    "Whispers_of_the_Abyss.png",
  ],
  bows: [
    "Ancient_Emberflight_Longbow.png",
    "Ancient_Emberflight_Recurve.png",
    "Ancient_Thornwood_Whisper.png",
    "Bloodthorn_Recurve.png",
    "Bonestring_Recurve.png",
    "Bonewood_Whisper.png",
    "Carrion's_Talon.png",
    "Carrionfeather_Longbow.png",
    "Crimson_Thornbow.png",
    "Cursed_Ebonwing_Recurve.png",
    "Cursed_Thornwood_Recurve.png",
    "Cursed_Thornwood_Whisper.png",
    "Duskwail_Recurve.png",
    "Ebonspine_Recurve.png",
    "Ebonwhisper_Longbow.png",
    "Ebonwing_Longbow.png",
    "Ebonwing_Recurve.png",
    "Ebonwood_Recurve.png",
    "Embercrest_Longbow.png",
    "Emberflight_Longbow.png",
    "Emberflight_Recurve.png",
    "Emberwood_Recurve.png",
    "Ember_Nightwhisper_Recurve.png",
    "Ember_Thornwood_Whisper.png",
    "Flamewing_Recurve.png",
    "Forsaken_Nightwhisper_Recurve.png",
    "Forsaken_Raven's_Talon_Bow.png",
    "Forsaken_Shadowpine_Recurve.png",
    "Forsaken_Stormwrath_Recurve.png",
    "Frostbite_Crescent.png",
    "Frostbite_Recurve.png",
    "Frostbite_Whisper.png",
    "Hollow_Sorrow's_Talon.png",
    "Hollow_Spinethorn_Recurve.png",
    "Hollow_Stormwrath_Recurve.png",
    "Nightfall_Crescent.png",
    "Nightfall_Recurve.png",
    "Nightwhisper_Recurve.png",
    "Nightwing_Recurve.png",
    "Ossein_Recurve.png",
    "Raven's_Descent.png",
    "Raven's_Lament.png",
    "Raven's_Requiem.png",
    "Raven's_Talon_Bow.png",
    "Ravenclaw_Longbow.png",
    "Ravenstrike_Longbow.png",
    "Scorchwing_Recurve.png",
    "Serpent's_Whisper_Bow.png",
    "Shadowbark_Recurve.png",
    "Shadowbind_Recurve.png",
    "Shadowfang_Recurve.png",
    "Shadowpiercer_Longbow.png",
    "Shadowpine_Recurve.png",
    "Shadowrend_Longbow.png",
    "Shattered_Bloodthorn_Recurve.png",
    "Shattered_Emberflight_Recurve.png",
    "Shattered_Thornwood_Whisper.png",
    "Sorrow's_Arc.png",
    "Sorrow's_Crescent.png",
    "Sorrow's_Talon.png",
    "Spinebark_Recurve.png",
    "Spinefang_Longbow.png",
    "Spinethorn_Longbow.png",
    "Spinethorn_Recurve.png",
    "Splinterfang_Longbow.png",
    "Stormfang_Recurve.png",
    "Stormfeather_Longbow.png",
    "Stormveil_Longbow.png",
    "Stormveil_Recurve.png",
    "Stormwing_Recurve.png",
    "Stormwrath_Crescent.png",
    "Stormwrath_Recurve.png",
    "Storm_Bloodthorn_Recurve.png",
    "Storm_Ossein_Recurve.png",
    "Storm_Raven's_Talon_Bow.png",
    "Storm_Shadowrend_Longbow.png",
    "Storm_Stormfang_Recurve.png",
    "Storm_Stormwrath_Recurve.png",
    "Storm_Thornwood_Whisper.png",
    "Thornwood_Crescent.png",
    "Thornwood_Recurve.png",
    "Thornwood_Requiem.png",
    "Thornwood_Talon.png",
    "Thornwood_Whisper.png",
    "Veilblight_Recurve.png",
    "Veilpiercer's_Talon.png",
    "Veilpiercer_Longbow.png",
    "Veilrend_Longbow.png",
    "Veilstrike_Longbow.png",
    "Voidborn_Frostbite_Whisper.png",
    "Voidborn_Shadowbind_Recurve.png",
    "Voidborn_Shadowpine_Recurve.png",
    "Voidborn_Thornwood_Recurve.png",
    "Voidborn_Thornwood_Whisper.png",
    "Voidborn_Thornwood_Whisper_2.png",
    "Voidborn_Thornwood_Whisper_3.png",
    "Voidpulse_Longbow.png",
    "Voidstrike_Recurve.png",
    "Whisperwind_Bow.png",
    "Wraithstring_Bow.png",
  ],
  staffs: [
    "Amethyst_Spiritbinder.png",
    "Amethyst_Thornscepter.png",
    "Ancient_Bloodthorn_Scepter.png",
    "Aurelion's_Crescent_Staff.png",
    "Azureblight_Scepter.png",
    "Azurebound_Scepter.png",
    "Azurespire_Staff.png",
    "Azurite_Scepter_of_Unmaking.png",
    "Azurite_Spirecaster.png",
    "Azurite_Spire_Staff.png",
    "Azurite_Thaumaturge's_Rod.png",
    "Bloodbloom_Scepter.png",
    "Bloodmoon_Scepter.png",
    "Bloodthorn_Catalyst.png",
    "Bloodthorn_Crook.png",
    "Bloodthorn_Scepter.png",
    "Bloomveil_Scepter.png",
    "Bonegnaw_Crook.png",
    "Bonelust_Crook.png",
    "Bonepulse_Scepter.png",
    "Bonepulse_Staff.png",
    "Bonewood_Conduit.png",
    "Bonewraith_Scepter.png",
    "Bonewraith_Staff.png",
    "Crescent_Voidstaff.png",
    "Crimson_Blight_Scepter.png",
    "Crimson_Conduit_Staff.png",
    "Crimson_Marrow_Staff.png",
    "Crimson_Spiraling_Wand.png",
    "Crimson_Thaumaturge's_Rod.png",
    "Cursed_Emberfang_Staff.png",
    "Cursed_Stormveil_Scepter.png",
    "Cursed_Thornbloom_Scepter.png",
    "Duskblight_Crook.png",
    "Duskwarden's_Crook.png",
    "Ebonspire_Conduit.png",
    "Ebonspire_Crook.png",
    "Embercinder's_Crook.png",
    "Embercinder_Staff.png",
    "Embercrown_Staff.png",
    "Emberfang_Conduit.png",
    "Emberfang_Scepter.png",
    "Emberfang_Staff.png",
    "Flamecrest_Scepter.png",
    "Forsaken_Bloodthorn_Scepter.png",
    "Forsaken_Starfall_Conduit.png",
    "Frostspire_Staff.png",
    "Frostweave_Conduit.png",
    "Frostwhisper_Conduit.png",
    "Hollow_Bloodthorn_Scepter.png",
    "Marrowveil_Scepter.png",
    "Obsidian_Veilstaff.png",
    "Ossein_Conduit.png",
    "Ossein_Conduit_Staff.png",
    "Ossein_Crook.png",
    "Ossein_Scepter.png",
    "Ossuary_Crook.png",
    "Ravenwing_Catalyst.png",
    "Runecarved_Scepter.png",
    "Rusted_Bonegnawer.png",
    "Sepulcher's_Reach.png",
    "Serpent's_Coil_Staff.png",
    "Serpent's_Covenant_Staff.png",
    "Shadowpulse_Scepter.png",
    "Shadowthorn_Crescent.png",
    "Shattered_Bloodthorn_Scepter.png",
    "Shattered_Emberfang_Staff.png",
    "Solstice_Arbor_Staff.png",
    "Solstice_Crook.png",
    "Soulroot_Staff.png",
    "Soulveil_Crook.png",
    "Soulweaver's_Crook.png",
    "Spiralveil_Crook.png",
    "Starfall_Conduit.png",
    "Starfall_Scepter.png",
    "Stormcaller's_Conduit.png",
    "Stormfang_Staff.png",
    "Stormveil_Scepter.png",
    "Storm_Bloodthorn_Scepter.png",
    "Storm_Crimson_Marrow_Staff.png",
    "Thornbloom_Catalyst.png",
    "Thornbloom_Scepter.png",
    "Thornspire_Catalyst.png",
    "Thornspire_Scepter.png",
    "Thornwick_Cataclysm.png",
    "Thornwick_Conduit.png",
    "Thornwood_Conduit.png",
    "Thornwood_Diviner's_Staff.png",
    "Umbralshard_Staff.png",
    "Veilmend_Crescent.png",
    "Veilpiercer's_Crook.png",
    "Veilshard_Scepter.png",
    "Veilstone_Scepter.png",
    "Veiltwist_Scepter.png",
    "Verdantis_Staff_of_Thorns.png",
    "Verdant_Scepter_of_Thorns.png",
    "Voidbloom_Scepter.png",
    "Voidborn_Bloodthorn_Crook.png",
    "Voidborn_Thornwood_Conduit.png",
    "Wraithbark_Scepter.png",
  ],
  helmets: [
    "Amethyst_Witch's_Crown.png",
    "Amethyst_Wrath_Helm.png",
    "Ancient_Embercrown_of_the_Fallen.png",
    "Ancient_Emberveil_Circlet.png",
    "Ancient_Grimscale_Helm.png",
    "Ancient_Grimscale_Helm_2.png",
    "Ancient_Grimscale_Helm_3.png",
    "Ancient_Grimscale_Helm_4.png",
    "Bonelace_Helm.png",
    "Bullhorn_Visage.png",
    "Crimson_Apex_Helm.png",
    "Crimson_Coronet_of_Thorns.png",
    "Crimson_Lotus_Crown.png",
    "Crimson_Marrow_Helm.png",
    "Crimson_Ossuary_Crown.png",
    "Crimson_Thane_Helm.png",
    "Crimson_Thorn_Crown.png",
    "Crimson_Thrall_Helm.png",
    "Crimson_Throne_Helm.png",
    "Crimson_Witch's_Helm.png",
    "Crown_of_the_Hollowed.png",
    "Cursed_Emberveil_Circlet.png",
    "Cursed_Grimscale_Coronet.png",
    "Cursed_Grimscale_Crown.png",
    "Duskwarden's_Cowl.png",
    "Duskwarden's_Helm.png",
    "Embercrest_Helm.png",
    "Embercrest_Sombrero.png",
    "Embercrown_Helm.png",
    "Embercrown_of_the_Fallen.png",
    "Embercrown_of_the_Pyre.png",
    "Emberhusk_Coronet.png",
    "Emberveil_Casque.png",
    "Emberveil_Circlet.png",
    "Emberveil_Coif.png",
    "Emberveil_Coronet.png",
    "Emberveil_Crown.png",
    "Emberveil_Helm.png",
    "Emberveil_Horns.png",
    "Ember_Grimscale_Coronet.png",
    "Forsaken_Embercrown_of_the_Fallen.png",
    "Forsaken_Emberveil_Crown.png",
    "Forsaken_Emberveil_Helm.png",
    "Forsaken_Emberveil_Helm_2.png",
    "Forsaken_Grimscale_Helm.png",
    "Grimbound_Casque.png",
    "Grimfeather_Helm.png",
    "Grimhorn_Helm.png",
    "Grimhorn_Visage.png",
    "Grimscale_Coronet.png",
    "Grimscale_Cowl.png",
    "Grimscale_Crown.png",
    "Grimscale_Helm.png",
    "Grimscout's_Helm.png",
    "Grimspike_Crown.png",
    "Grimspire_Crown.png",
    "Grimvault_Helm.png",
    "Grimveil_Casque.png",
    "Grimveil_Coronet.png",
    "Grimveil_Helm.png",
    "Grimveil_Sorcerer's_Cap.png",
    "Grimwood_Coronet.png",
    "Hollowveil_Helm.png",
    "Hollowveil_Skull_Helm.png",
    "Hollow_Embercrown_of_the_Fallen.png",
    "Hollow_Embercrown_of_the_Fallen_2.png",
    "Hollow_Emberveil_Casque.png",
    "Hollow_Grimscale_Coronet.png",
    "Hollow_Grimscale_Cowl.png",
    "Hollow_Grimscale_Helm.png",
    "Horned_Tyrant's_Crown.png",
    "Ironbound_Grimhelm.png",
    "Moss-Worn_Helm_of_Thorns.png",
    "Nightshade_Circlet.png",
    "Nightshade_Witch's_Helm.png",
    "Shadowmere_Helm.png",
    "Shadowpeak_Helm.png",
    "Shattered_Emberveil_Helm.png",
    "Shattered_Grimscale_Cowl.png",
    "Shattered_Grimscale_Helm.png",
    "Solstice_Crown.png",
    "Starweaver's_Cowl.png",
    "Storm_Embercrest_Helm.png",
    "Storm_Emberveil_Helm.png",
    "Storm_Emberveil_Helm_2.png",
    "Storm_Thornwood_Crown.png",
    "Tauric_Dread_Helm.png",
    "Thornscale_Helm.png",
    "Thornwood_Crown.png",
    "Toadkin_Bulwark.png",
    "Veilbound_Crown.png",
    "Voidborn_Emberveil_Helm.png",
    "Voidborn_Grimscale_Coronet.png",
    "Voidborn_Grimscale_Coronet_2.png",
    "Voidborn_Grimscale_Helm.png",
    "Voidborn_Grimscale_Helm_2.png",
    "Voidborn_Grimscale_Helm_3.png",
    "Voidborn_Grimscale_Helm_4.png",
    "Voidwraith_Helm.png",
    "Witchpyre_Helm.png",
  ],
  plates: [
    "Ancient_Bloodweave_Cuirass.png",
    "Ancient_Bloodweave_Cuirass_2.png",
    "Ancient_Embercrest_Cuirass.png",
    "Ashplate_Harness.png",
    "Azuremantle_Cuirass.png",
    "Azurite_Tyrant's_Carapace.png",
    "Azurite_Warden's_Mantle.png",
    "Blackthorn_Cuirass.png",
    "Bloodbound_Cuirass.png",
    "Bloodforged_Harness.png",
    "Bloodhewn_Cuirass.png",
    "Bloodleather_Cuirass.png",
    "Bloodleather_Harness.png",
    "Bloodmoon_Cuirass.png",
    "Bloodplate_Carapace.png",
    "Bloodplate_Cuirass.png",
    "Bloodplate_Haubergeon.png",
    "Bloodrite_Cuirass.png",
    "Bloodscale_Breastplate.png",
    "Bloodscourge_Cuirass.png",
    "Bloodstitched_Doublet.png",
    "Bloodthorn_Cuirass.png",
    "Bloodweave_Cuirass.png",
    "Bloodweave_Hauberk.png",
    "Bloodworn_Cuirass.png",
    "Bonelord's_Carapace.png",
    "Bonelord's_Cuirass.png",
    "Bronzeplate_of_the_Fallen.png",
    "Burnished_Dreadplate.png",
    "Crimson_Harbinger_Plate.png",
    "Crimson_Thornplate.png",
    "Crimson_Throneguard.png",
    "Cursed_Bloodweave_Cuirass.png",
    "Cursed_Bloodweave_Cuirass_2.png",
    "Cursed_Bloodweave_Cuirass_3.png",
    "Cursed_Thornplate_Cuirass.png",
    "Duskplate_Harness.png",
    "Emberclaw_Cuirass.png",
    "Embercrest_Breastplate.png",
    "Embercrest_Cuirass.png",
    "Embercrest_Harness.png",
    "Embercrown_Cuirass.png",
    "Emberscourge_Cuirass.png",
    "Ember_Bloodweave_Cuirass.png",
    "Ember_Ironbound_Thoraxplate.png",
    "Forsaken_Ironpact_Breastplate.png",
    "Goldbound_Thoraxplate.png",
    "Goldenscale_Cuirass.png",
    "Goldplate_Sentinel.png",
    "Goldvein_Warplate.png",
    "Goldweave_Breastplate.png",
    "Goldweave_Cuirass.png",
    "Hollow_Bloodrite_Cuirass.png",
    "Hollow_Bloodweave_Cuirass.png",
    "Hollow_Ironpact_Cuirass.png",
    "Ironbark_Cuirass.png",
    "Ironbound_Ashvest.png",
    "Ironbound_Bulwark.png",
    "Ironbound_Cuirass_of_the_Bloodmarch.png",
    "Ironbound_Reaver's_Plate.png",
    "Ironbound_Thoraxplate.png",
    "Ironpact_Breastplate.png",
    "Ironpact_Cuirass.png",
    "Ironwood_Warplate.png",
    "Marrowplate_Hauberk.png",
    "Nightpurple_Cuirass.png",
    "Rotwood_Cuirass.png",
    "Shadowplate_Corselet.png",
    "Shadowplate_Haubergeon.png",
    "Shattered_Embercrest_Cuirass.png",
    "Shattered_Thornplate_Cuirass.png",
    "Shattered_Thornplate_Cuirass_2.png",
    "Storm_Thornplate_Cuirass.png",
    "Storm_Voidthorn_Cuirass.png",
    "Sundered_Breastplate.png",
    "Thornbound_Cuirass.png",
    "Thorncrest_Cuirass.png",
    "Thornhide_Cuirass.png",
    "Thornplate_Cuirass.png",
    "Thornscale_Breastplate.png",
    "Thornscale_Cuirass.png",
    "Thornscale_Harness.png",
    "Thornveil_Cuirass.png",
    "Thornweave_Cuirass.png",
    "Thornweave_Hauberk.png",
    "Thornwood_Carapace.png",
    "Thornwood_Pauldrons.png",
    "Umbral_Carapace.png",
    "Veilbound_Cuirass.png",
    "Voidborn_Emberclaw_Cuirass.png",
    "Voidborn_Emberclaw_Cuirass_2.png",
    "Voidborn_Goldenscale_Cuirass.png",
    "Voidborn_Goldweave_Breastplate.png",
    "Voidborn_Ironbark_Cuirass.png",
    "Voidborn_Ironbound_Thoraxplate.png",
    "Voidborn_Thornscale_Cuirass.png",
    "Voidforged_Cuirass.png",
    "Voidpact_Cuirass.png",
    "Voidthorn_Cuirass.png",
    "Weavemesh_Brigandine.png",
  ],
  mantles: [
    "Ancient_Shadowveil_Mantle.png",
    "Ancient_Shadowweave_Mantle.png",
    "Ancient_Shadowweave_Mantle_2.png",
    "Ancient_Shadowweave_Mantle_3.png",
    "Ancient_Veilstorm_Mantle.png",
    "Ancient_Veilwraith_Mantle.png",
    "Ashenheart_Mantle.png",
    "Ashwood_Shroud.png",
    "Azurite_Veil_Mantle.png",
    "Carmesine_Shroud.png",
    "Crimson_Thornmantle.png",
    "Crimson_Veilcloak.png",
    "Cursed_Emberfell_Mantle.png",
    "Cursed_Shadowpall_Mantle.png",
    "Cursed_Shadowveil_Mantle.png",
    "Cursed_Shadowveil_Mantle_2.png",
    "Cursed_Shadowveil_Mantle_3.png",
    "Cursed_Shadowweave_Mantle.png",
    "Cursed_Shadowweave_Mantle_2.png",
    "Duskwarden's_Mantle.png",
    "Duskweave_Mantle.png",
    "Embercinder_Mantle.png",
    "Embercrimson_Mantle.png",
    "Emberfell_Mantle.png",
    "Emberveil_Mantle.png",
    "Ember_Ravenwing_Mantle.png",
    "Ember_Shadowpall_Mantle.png",
    "Ember_Shadowpall_Mantle_2.png",
    "Ember_Shadowveil_Mantle.png",
    "Ember_Shadowveil_Mantle_2.png",
    "Ember_Shadowveil_Mantle_3.png",
    "Ember_Shadowveil_Mantle_4.png",
    "Ember_Shadowweave_Mantle.png",
    "Forsaken_Crimson_Veilcloak.png",
    "Forsaken_Shadowpall_Mantle.png",
    "Forsaken_Shadowweave_Mantle.png",
    "Forsaken_Shadowweave_Mantle_2.png",
    "Forsaken_Shadowweave_Mantle_3.png",
    "Forsaken_Thornweave_Mantle.png",
    "Forsaken_Thornweave_Mantle_2.png",
    "Forsaken_Veilweaver's_Shroud.png",
    "Forsaken_Veilwraith_Mantle.png",
    "Frostweaver's_Mantle.png",
    "Frostweave_Mantle.png",
    "Goldenweave_Shroud.png",
    "Goldweave_Mantle.png",
    "Goldweave_Shroud.png",
    "Hollow_Embercrimson_Mantle.png",
    "Hollow_Ravenwing_Mantle.png",
    "Hollow_Ravenwing_Shroud.png",
    "Hollow_Shadowveil_Mantle.png",
    "Hollow_Shadowveil_Mantle_2.png",
    "Hollow_Shadowweave_Mantle.png",
    "Hollow_Veilweaver's_Shroud.png",
    "Ravenwing_Mantle.png",
    "Ravenwing_Shroud.png",
    "Saffronveil_Mantle.png",
    "Shadowpall_Mantle.png",
    "Shadowpall_Vestment.png",
    "Shadowpine_Drape.png",
    "Shadowveil_Mantle.png",
    "Shadowweave_Mantle.png",
    "Shadowweft_Mantle.png",
    "Shattered_Frostweave_Mantle.png",
    "Shattered_Shadowveil_Mantle.png",
    "Shattered_Shadowveil_Mantle_2.png",
    "Shattered_Shadowweave_Mantle.png",
    "Shattered_Shadowweave_Mantle_2.png",
    "Shattered_Shadowweave_Mantle_3.png",
    "Shattered_Thornwood_Shroud.png",
    "Shattered_Veilwraith_Mantle.png",
    "Shroudweaver's_Mantle.png",
    "Shroud_of_the_Void.png",
    "Shroud_of_the_Withered_Oath.png",
    "Starfall_Mantle.png",
    "Stormweft_Mantle.png",
    "Storm_Shadowpall_Vestment.png",
    "Storm_Shadowveil_Mantle.png",
    "Storm_Shadowveil_Mantle_2.png",
    "Storm_Shadowveil_Mantle_3.png",
    "Storm_Shadowweave_Mantle.png",
    "Storm_Thornweave_Mantle.png",
    "Storm_Veilwraith_Mantle.png",
    "Thornveil_Mantle.png",
    "Thornweave_Mantle.png",
    "Thornwood_Shroud.png",
    "Veilmantle_of_the_Starless.png",
    "Veilshroud_Mantle.png",
    "Veilstitched_Mantle.png",
    "Veilstorm_Mantle.png",
    "Veilwarden's_Shroud.png",
    "Veilweaver's_Mantle.png",
    "Veilweaver's_Shroud.png",
    "Veilwraith_Mantle.png",
    "Voidborn_Shadowveil_Mantle.png",
    "Voidborn_Shadowweave_Mantle.png",
    "Voidborn_Shadowweave_Mantle_2.png",
    "Voidborn_Shadowweave_Mantle_3.png",
    "Voidborn_Thornweave_Mantle.png",
    "Voidweaver's_Mantle.png",
  ],
  gloves: [
    "Amethyst_Covenant_Gloves.png",
    "Ancient_Bloodhide_Gauntlets.png",
    "Ancient_Bloodwraith_Grips.png",
    "Ancient_Bloodwraith_Grips_2.png",
    "Ancient_Bonegrip_Gauntlets.png",
    "Ancient_Nightfall_Grips.png",
    "Ashen_Condemner's_Grips.png",
    "Ashen_Covenant_Wraps.png",
    "Ashen_Fist_Wraps.png",
    "Ashen_Frostgrips.png",
    "Ashen_Gauntlets_of_the_Void.png",
    "Ashen_Grips.png",
    "Ashen_Knucklebound_Wraps.png",
    "Azurite_Grips_of_the_Void.png",
    "Bindleather_Wraps.png",
    "Bloodhide_Gauntlets.png",
    "Bloodhide_Grips.png",
    "Bloodhound's_Grasp.png",
    "Bloodhusk_Grips.png",
    "Bloodleather_Gauntlets.png",
    "Bloodleather_Grips.png",
    "Bloodpulse_Wraps.png",
    "Bloodrite_Gauntlets.png",
    "Bloodrust_Gauntlets.png",
    "Bloodsoaked_Wraiths.png",
    "Bloodthorn_Gauntlets.png",
    "Bloodveil_Gauntlets.png",
    "Bloodveil_Grips.png",
    "Bloodveil_Wraps.png",
    "Bloodwarden_Gauntlets.png",
    "Bloodweaver's_Grasp.png",
    "Bloodweave_Gauntlets.png",
    "Bloodweave_Grips.png",
    "Bloodwoven_Gauntlets.png",
    "Bloodwraith_Gauntlets.png",
    "Bloodwraith_Grips.png",
    "Bone-Stitched_Grips.png",
    "Bonegrip_Gauntlets.png",
    "Bonewraith_Gauntlets.png",
    "Charred_Bone_Grips.png",
    "Crimson_Grasp_Wraps.png",
    "Crimson_Thorngrips.png",
    "Cursed_Bonegrip_Gauntlets.png",
    "Dreadbound_Gauntlets.png",
    "Duskmire_Gauntlets.png",
    "Embercinder_Grips.png",
    "Emberflare_Gauntlets.png",
    "Ember_Ashen_Grips.png",
    "Ember_Ashen_Grips_2.png",
    "Ember_Bloodhide_Grips.png",
    "Ember_Bloodhide_Grips_2.png",
    "Ember_Bloodleather_Grips.png",
    "Ember_Veilwraith_Grips.png",
    "Forsaken_Bloodhide_Gauntlets.png",
    "Forsaken_Bloodhide_Grips.png",
    "Forsaken_Veilwraith_Grips.png",
    "Frostblight_Wraiths.png",
    "Frostbrand_Gauntlets.png",
    "Frostweaver's_Grasp.png",
    "Hollow_Bloodhide_Gauntlets.png",
    "Hollow_Bloodleather_Grips.png",
    "Hollow_Crimson_Thorngrips.png",
    "Ironbound_Grips_of_Ruin.png",
    "Ironwood_Grips.png",
    "Nightfall_Grips.png",
    "Ossein_Grips.png",
    "Ossein_Wraiths'_Grasp.png",
    "Pestilent_Grasp_Gloves.png",
    "Rotwood_Gauntlets.png",
    "Scorched_Covenant_Gauntlets.png",
    "Scourgebound_Gauntlets.png",
    "Shadowbound_Gauntlets.png",
    "Shadowbound_Grips.png",
    "Shadowpact_Grips.png",
    "Shadowthread_Grips.png",
    "Shadowveil_Grips.png",
    "Shattered_Ashen_Grips.png",
    "Shattered_Bloodwraith_Gauntlets.png",
    "Shattered_Veilweaver's_Grasp.png",
    "Stormwrath_Grips.png",
    "Storm_Bloodhide_Grips.png",
    "Storm_Bloodhide_Grips_2.png",
    "Storm_Bloodrite_Gauntlets.png",
    "Thornveil_Gauntlets.png",
    "Thornweave_Gauntlets.png",
    "Veilbound_Grips.png",
    "Veilweaver's_Grasp.png",
    "Veilwraith_Grips.png",
    "Verdantcreep_Gauntlets.png",
    "Verdant_Blight_Wraps.png",
    "Void-Touched_Grips.png",
    "Voidborn_Bloodhide_Gauntlets.png",
    "Voidborn_Bloodhide_Gauntlets_2.png",
    "Voidborn_Bloodhide_Gauntlets_3.png",
    "Voidborn_Bloodhusk_Grips.png",
    "Withered_Thorngrips.png",
    "Wraithbone_Gauntlets.png",
    "Wraithbound_Gauntlets.png",
    "Wraithbound_Grips.png",
    "Wraithgrip_Gauntlets.png",
  ],
  belts: [
    "Abyssal_Cinch.png",
    "Abyssal_Cinture.png",
    "Ancient_Bloodwraith_Girdle.png",
    "Ancient_Cinderbound_Girdle.png",
    "Ancient_Cinderbound_Girdle_2.png",
    "Ancient_Shadowbound_Girdle.png",
    "Ancient_Voidbound_Girdle.png",
    "Ancient_Wraithbound_Girdle.png",
    "Blackthorn_Cinch.png",
    "Bloodbound_Cinch.png",
    "Bloodbound_Girdle.png",
    "Bloodbraid_Cinch.png",
    "Bloodthorn_Cincture.png",
    "Bloodvow_Girdle.png",
    "Bloodwarden's_Cincture.png",
    "Bloodweave_Girdle.png",
    "Bloodwraith_Girdle.png",
    "Bloodwrath_Girdle.png",
    "Boneweave_Girdle.png",
    "Carrionscale_Cinch.png",
    "Carrionwraith_Girdle.png",
    "Cinderbound_Girdle.png",
    "Cinderbrand_Girdle.png",
    "Cinderclasp_Girdle.png",
    "Cindercord_Girdle.png",
    "Cinderfang_Girdle.png",
    "Cindergilt_Waistband.png",
    "Cordage_of_the_Void.png",
    "Cordwainer's_Cinch.png",
    "Crimson_Girdle_of_Dominion.png",
    "Crimson_Tyrant's_Cinch.png",
    "Crimson_Tyrant's_Girdle.png",
    "Crimson_Warden's_Girdle.png",
    "Cursed_Bloodbound_Cinch.png",
    "Cursed_Shadowbound_Girdle.png",
    "Deathbound_Girdle.png",
    "Deathgrip_Cinch.png",
    "Dreadwhisper_Girdle.png",
    "Embercinder_Girdle.png",
    "Embercord_Girdle.png",
    "Ember_Cinderbound_Girdle.png",
    "Ember_Cinderbound_Girdle_2.png",
    "Ember_Embercinder_Girdle.png",
    "Forsaken_Bloodbound_Cinch.png",
    "Forsaken_Bloodwraith_Girdle.png",
    "Forsaken_Cinderbound_Girdle.png",
    "Forsaken_Cinderbound_Girdle_2.png",
    "Forsaken_Cinderbound_Girdle_3.png",
    "Forsaken_Cinderbound_Girdle_4.png",
    "Forsaken_Embercord_Girdle.png",
    "Goldleaf_Cinch.png",
    "Hollow_Cinderbound_Girdle.png",
    "Hollow_Cinderbound_Girdle_2.png",
    "Hollow_Cinderbound_Girdle_3.png",
    "Hollow_Ironpact_Girdle.png",
    "Ironbound_Wayfarer's_Girdle.png",
    "Ironpact_Cinch.png",
    "Ironpact_Girdle.png",
    "Ironpact_Waistguard.png",
    "Nightbound_Cinch.png",
    "Nightbound_Girdle.png",
    "Nightscourge_Cinch.png",
    "Riftbound_Girdle.png",
    "Scourgebound_Girdle.png",
    "Shadowbind_Cincture.png",
    "Shadowbound_Girdle.png",
    "Shadowpact_Cincture.png",
    "Shadowpact_Girdle.png",
    "Shattered_Cinderbound_Girdle.png",
    "Shattered_Cinderbound_Girdle_2.png",
    "Shattered_Cinderbound_Girdle_3.png",
    "Shattered_Cinderbound_Girdle_4.png",
    "Shattered_Shadowbound_Girdle.png",
    "Shattered_Wraithbound_Girdle.png",
    "Storm_Abyssal_Cinch.png",
    "Storm_Cinderbound_Girdle.png",
    "Storm_Cinderbound_Girdle_2.png",
    "Storm_Cinderbound_Girdle_3.png",
    "Storm_Cinderbound_Girdle_4.png",
    "Storm_Wraithbound_Girdle.png",
    "Tarnished_Corslet_Girdle.png",
    "Thornwraith_Girdle.png",
    "Verdant_Cinch_of_Thorns.png",
    "Verdant_Girdle_of_Thorns.png",
    "Verdant_Siege_Girdle.png",
    "Verdant_Warden's_Girdle.png",
    "Void-Stitched_Cinch.png",
    "Voidbinder's_Cinch.png",
    "Voidbinder's_Girdle.png",
    "Voidborn_Cinderbound_Girdle.png",
    "Voidborn_Cinderbound_Girdle_2.png",
    "Voidborn_Cinderbound_Girdle_3.png",
    "Voidborn_Cinderbound_Girdle_4.png",
    "Voidbound_Girdle.png",
    "Voidpact_Cincture.png",
    "Voidstitched_Girdle.png",
    "Voidwarden's_Cinch.png",
    "Voidweft_Girdle.png",
    "Voidwraith_Cincture.png",
    "Wraithbound_Girdle.png",
  ],
  boots: [
    "Abyssal_Stride_Boots.png",
    "Abyssal_Treads.png",
    "Amethyst_Marrow_Treads.png",
    "Ancient_Abyssal_Treads.png",
    "Ancient_Bloodmire_Treads.png",
    "Ash-Treader_Boots.png",
    "Ashenblight_Treads.png",
    "Ashencinder_Treads.png",
    "Ashenclaw_Greaves.png",
    "Ashenclomp_Treads.png",
    "Ashencreep_Treads.png",
    "Ashenmire_Treads.png",
    "Ashenstep_Sabatons.png",
    "Ashenworn_Greaves.png",
    "Ashen_Treader_Boots.png",
    "Ashen_Wanderer's_Boots.png",
    "Ashen_Wanderer's_Treads.png",
    "Ashwalker's_Greaves.png",
    "Ashwalker's_Treads.png",
    "Azurite_Strider's_Boots.png",
    "Bloodhoof_Treads.png",
    "Bloodmire_Greaves.png",
    "Bloodmire_Treads.png",
    "Bloodrust_Treaders.png",
    "Bloodthorn_Greaves.png",
    "Cindercrust_Greaves.png",
    "Cindercrust_Treads.png",
    "Cinderfang_Treads.png",
    "Cinderfell_Treads.png",
    "Cinderstep_Treads.png",
    "Cinders_of_the_Fallen.png",
    "Crimson_Marrow_Treads.png",
    "Crimson_Shroud_Treads.png",
    "Crimson_Void_Treads.png",
    "Cursed_Duskmarrow_Treads.png",
    "Cursed_Embercinder_Treads.png",
    "Cursed_Shadowpact_Greaves.png",
    "Cursed_Stormveil_Treads.png",
    "Dreadstep_Greaves.png",
    "Dreadstep_Treads.png",
    "Duskbound_Greaves.png",
    "Duskmarrow_Treads.png",
    "Duskstep_Greaves.png",
    "Embercinder_Treads.png",
    "Emberscorch_Treads.png",
    "Emberscourge_Treads.png",
    "Ember_Ashwalker's_Treads.png",
    "Ember_Embercinder_Treads.png",
    "Forsaken_Embercinder_Treads.png",
    "Forsaken_Shadowstep_Greaves.png",
    "Forsaken_Shadowstep_Greaves_2.png",
    "Frostbind_Greaves.png",
    "Frostbind_Treads.png",
    "Frostpeak_Treads.png",
    "Hollow_Ashenstep_Sabatons.png",
    "Hollow_Emberscorch_Treads.png",
    "Hollow_Frostbind_Treads.png",
    "Hollow_Shadowstep_Greaves.png",
    "Ironpeak_Striders.png",
    "Marrowstep_Treads.png",
    "Marshrot_Treads.png",
    "Mossgrown_Treaders.png",
    "Mossgrown_Treads.png",
    "Mossveil_Treads.png",
    "Nightbloom_Treads.png",
    "Nightfall_Treads.png",
    "Nightshade_Treads.png",
    "Nightveil_Greaves.png",
    "Sapphire_Warden's_Greaves.png",
    "Scorched_Ember_Treads.png",
    "Scorched_Wanderer's_Treads.png",
    "Shadowpace_Sabatons.png",
    "Shadowpact_Greaves.png",
    "Shadowpact_Treads.png",
    "Shadowstep_Greaves.png",
    "Shadowstep_Treads.png",
    "Shattered_Embercinder_Treads.png",
    "Shattered_Embercinder_Treads_2.png",
    "Shattered_Shadowstep_Greaves.png",
    "Soulstep_Treads.png",
    "Stonewraith_Treads.png",
    "Stormveil_Treads.png",
    "Storm_Abyssal_Treads.png",
    "Storm_Mossgrown_Treads.png",
    "Storm_Umbral_Treads.png",
    "Swampblight_Treads.png",
    "Thornroot_Treads.png",
    "Thornveil_Treads.png",
    "Tidecaller's_Treads.png",
    "Umbralshard_Treads.png",
    "Umbral_Talons.png",
    "Umbral_Treads.png",
    "Veilstep_Treads.png",
    "Verdant_Blight_Treads.png",
    "Verdant_Mire_Treads.png",
    "Verdigris_Stalkers.png",
    "Voidborn_Bloodmire_Treads.png",
    "Voidborn_Embercinder_Treads.png",
    "Voidborn_Shadowstep_Greaves.png",
    "Voidborn_Shadowstep_Greaves_2.png",
  ],
  rings: [
    "Abyssal_Signet.png",
    "Amethyst_Sigil_of_Whispers.png",
    "Ancient_Embercrest_Sigil.png",
    "Ashborn_Signet.png",
    "Ashbound_Signet.png",
    "Aurelion's_Sealed_Oath.png",
    "Aurelius_Band.png",
    "Aurumblight_Signet.png",
    "Azurite_Covenant_Ring.png",
    "Azurite_Oath_Ring.png",
    "Azurite_Seal_Ring.png",
    "Bearskull_Signet.png",
    "Bloodember_Sigil.png",
    "Bloodpact_Sigil.png",
    "Bloodthorn_Sigil.png",
    "Covenant_of_Cinders.png",
    "Crimson_Sovereignty_Ring.png",
    "Crimson_Thorn_Sigil.png",
    "Cursed_Serpent's_Coil_Ring.png",
    "Cursed_Voidpulse_Sigil.png",
    "Embercinder's_Seal.png",
    "Embercircle_of_the_Pyre.png",
    "Embercircle_Sigil.png",
    "Emberclaw_Sigil.png",
    "Embercrest_Sigil.png",
    "Emberfang_Sigil.png",
    "Emberforge_Signet.png",
    "Emberlight_Signet.png",
    "Emberwraith_Sigil.png",
    "Ember_Soulbound_Signet.png",
    "Ember_Thornwraith_Sigil.png",
    "Forsaken_Abyssal_Signet.png",
    "Forsaken_Obsidian_Covenant_Ring.png",
    "Forsaken_Serpent's_Coil_Ring.png",
    "Forsaken_Serpent's_Covenant_Ring.png",
    "Forsaken_Soulbound_Circlet.png",
    "Frostwhisper_Sigil.png",
    "Goldbound_Sigil.png",
    "Goldenrust_Sigil.png",
    "Goldleaf_Covenant_Ring.png",
    "Goldroot_Sigil.png",
    "Goldspire_Signet.png",
    "Goldwraith_Sigil.png",
    "Goldwraith_Signet.png",
    "Grimwood_Sigil.png",
    "Hollow_Serpent's_Coil_Ring.png",
    "Hollow_Serpent's_Coil_Ring_2.png",
    "Nightfall_Signet.png",
    "Nightwraith's_Covenant.png",
    "Oathkeeper's_Seal.png",
    "Obsidian_Covenant_Ring.png",
    "Obsidian_Sigil_Ring.png",
    "Ossein_Signet.png",
    "Owlheart_Sigil.png",
    "Ravenclaw_Sigil.png",
    "Ringveil_of_Forgotten_Oaths.png",
    "Sable_Oath_Sigil.png",
    "Sapphire_Dominion_Ring.png",
    "Sapphire_Oath_Ring.png",
    "Serpent's_Coil_Ring.png",
    "Serpent's_Covenant_Ring.png",
    "Serpentbone_Sigil.png",
    "Serpentine_Covenant_Ring.png",
    "Shattered_Embercrest_Sigil.png",
    "Sigil_of_the_Withered_Crown.png",
    "Signet_of_the_Goldwrath.png",
    "Sorrow's_Coil.png",
    "Sorrow's_Covenant_Ring.png",
    "Soulbound_Circlet.png",
    "Soulbound_Signet.png",
    "Soulvault_Signet.png",
    "Soulweave_Sigil.png",
    "Sovereign's_Seal.png",
    "Spiralbound_Signet.png",
    "Spiralveil_Sigil.png",
    "Stormveil_Sigil.png",
    "Storm_Embercrest_Sigil.png",
    "Thornheart_Sigil.png",
    "Thornweave_Signet.png",
    "Thornwood_Covenant_Ring.png",
    "Thornwood_Sigil.png",
    "Thornwraith_Sigil.png",
    "Tidecaller's_Sigil.png",
    "Umbral_Covenant_Ring.png",
    "Veilstone_Sigil.png",
    "Veilstone_Signet.png",
    "Verdant_Sigil_Ring.png",
    "Verdant_Thrall_Ring.png",
    "Verdant_Throne_Ring.png",
    "Verdant_Warden's_Seal.png",
    "Voidborn_Obsidian_Covenant_Ring.png",
    "Voidborn_Serpent's_Coil_Ring.png",
    "Voidborn_Serpent's_Coil_Ring_2.png",
    "Voidheart_Ring.png",
    "Voidheart_Signet.png",
    "Voidpact_Signet.png",
    "Voidpulse_Sigil.png",
    "Voidspiral_Signet.png",
    "Warden's_Seal_Ring.png",
    "Wraithbound_Sigil.png",
  ],
  amulets: [
    "Abyssal_Anchor.png",
    "Abyssal_Sigil.png",
    "Abyssal_Tide_Pendant.png",
    "Arachnid's_Malice.png",
    "Astral_Warden's_Sigil.png",
    "Azurite_Watcher's_Seal.png",
    "Azurite_Watcher's_Talisman.png",
    "Bloodbound_Keystone.png",
    "Bloodhound's_Talisman.png",
    "Bloodpact_Sigil.png",
    "Bloodpact_Talisman.png",
    "Bloodveil_Sigil.png",
    "Bloodwing_Sigil.png",
    "Bloodwood_Effigy.png",
    "Bonelord's_Vigil.png",
    "Carrionfeeder's_Grasp.png",
    "Carved_Maw_of_Thaal.png",
    "Chalice_of_Cinders.png",
    "Chalice_of_Remnant_Echoes.png",
    "Crescent_Veilmark.png",
    "Crimson_Covenant_Heart.png",
    "Crimson_Heartstone.png",
    "Crimson_Oath_Medallion.png",
    "Crimson_Runeheart.png",
    "Crimson_Seal_Amulet.png",
    "Crimson_Tether_Amulet.png",
    "Crimson_Vigil_Amulet.png",
    "Crimson_Warden's_Seal.png",
    "Crossveil_Aegis.png",
    "Deathshead_Sigil.png",
    "Deepward_Anchor.png",
    "Demonfire_Crest.png",
    "Dreadwing_Talisman.png",
    "Duskwarden's_Fang.png",
    "Duskwarden's_Tear.png",
    "Embercrest_Amulet.png",
    "Emberfang_Talisman.png",
    "Emberscourge_Talisman.png",
    "Ember_Sentinel's_Heart.png",
    "Fang_of_the_Abyss.png",
    "Feathered_Veil_Amulet.png",
    "Gilded_Redemption_Cross.png",
    "Godstone_Ankh.png",
    "Goldwarden's_Eye.png",
    "Heartwing_Pendant.png",
    "Hollowveil_Talisman.png",
    "Iris_of_the_Void.png",
    "Ironbound_Warden's_Seal.png",
    "Latticebound_Talisman.png",
    "Leonine_Voidheart.png",
    "Luneblight_Charm.png",
    "Nightbound_Talisman.png",
    "Nightwheel_Sigil.png",
    "Obsidian_Wardmoth_Amulet.png",
    "Owlseer's_Vigil.png",
    "Owlwatcher's_Vigil.png",
    "Pawbound_Talisman.png",
    "Pyramid_of_the_All-Seeing.png",
    "Radiant_Aegis_Pendant.png",
    "Raven's_Covenant.png",
    "Raven's_Hollow_Eye.png",
    "Raven's_Hollow_Talisman.png",
    "Rootbound_Covenant.png",
    "Sable_Serpent's_Oath.png",
    "Sapphire_Wardstone.png",
    "Scarab_of_Eternal_Vigil.png",
    "Serpent's_Coil_Amulet.png",
    "Serpent's_Covenant.png",
    "Serpent's_Oath_Amulet.png",
    "Serpent's_Ouroboros.png",
    "Shadowpact_Talisman.png",
    "Skullthorn_Pendant.png",
    "Slate_of_the_Abyss.png",
    "Solaris_Oath_Amulet.png",
    "Solheart_Amulet.png",
    "Solstice's_Burning_Eye.png",
    "Sorrow's_Aegis_Pendant.png",
    "Soulwing_Locket.png",
    "Sovereign's_Blight.png",
    "Sovereign's_Blight_Crown.png",
    "Starfall_Sigil.png",
    "Stormveil_Sigil.png",
    "Storm_Serpent's_Covenant.png",
    "Teardrop_of_the_Abyss.png",
    "Tidecaller's_Sigil.png",
    "Tortoiseshell_Aegis.png",
    "Veilbound_Keystone.png",
    "Veilbound_Talisman.png",
    "Veilwarden_Amulet.png",
    "Verdant_Carapace_Sigil.png",
    "Verdant_Eye_Talisman.png",
    "Verdant_Scarab_Amulet.png",
    "Verdant_Sorrow_Pendant.png",
    "Verdant_Star_Talisman.png",
    "Verdant_Teardrop_Amulet.png",
    "Violet_Seer's_Pendant.png",
    "Voidborn_Serpent's_Covenant.png",
    "Wingward_Sigil.png",
    "Wolfpact_Sigil.png",
    "Wornhide_Phylactery.png",
  ],
};

/**
 * In-use icon filenames per set (only these are used in-game).
 * Each item gets a unique display name and stat pool based on its filename.
 */
const IN_USE_ICONS: Record<string, string[]> = {
  swords: [
    "Ancient_Thornspire_Cleaver.png", "Ashborn_Katana.png", "Ashenbrand_Cleaver.png",
    "Bloodoak_Cleaver.png", "Cursed_Azureblight_Cleaver.png", "Cursed_Duskfang_Cleaver.png",
    "Duskbrand_Cleaver.png", "Duskfall_Cleaver.png", "Ember_Emberfang_Cleaver.png",
    "Embercleaver_Sabre.png", "Frostbane_Cleaver.png", "Glacial_Fang_Blade.png",
    "Goldflare_Cleaver.png", "Hollow_Emberfang_Cleaver_2.png", "Nightpurge_Cleaver.png",
    "Shattered_Emberfang_Cleaver.png", "Storm_Duskfang_Cleaver.png", "Tideborne_Cleaver.png",
    "Veilpiercer's_Edge.png", "Veilpiercer_Blade.png",
  ],
  axes: [
    "Blackpine_Reaper.png", "Bloodaxe_of_the_Forsaken.png", "Bloodfang_Cleaver.png",
    "Bloodmoon_Reaver.png", "Bloodpeak_Reaper.png", "Bloodreaver's_Cleave.png",
    "Bloodrusted_Cleaver.png", "Bloodthorn_Reaper.png", "Cursed_Bloodmoon_Cleaver.png",
    "Ember_Bloodrite_Cleaver.png", "Emberfell_Cleaver.png", "Grimstone_Reaper.png",
    "Hollow_Bloodmoon_Cleaver_4.png", "Hollow_Bloodrite_Cleaver.png",
    "Shattered_Bloodmoon_Cleaver.png", "Shattered_Bloodpeak_Cleaver.png",
    "Storm_Bloodrite_Cleaver.png", "Stormbreaker's_Maul.png", "Thornblight_Cleaver.png",
    "Voidborn_Bloodmoon_Cleaver_3.png",
  ],
  blades: [
    "Amethyst_Fang.png", "Ashblight_Dirk.png", "Azureblight_Katana.png",
    "Crescent_Fang.png", "Crimson_Marrow_Blade.png", "Crimson_Marrow_Cleaver.png",
    "Crimson_Talon_Blade.png", "Ember_Nightfall_Cleaver.png", "Frostbrand_Katana.png",
    "Hollow_Amethyst_Blight.png", "Hollow_Crimson_Blight_Cleaver.png", "Hollow_Talon.png",
    "Nightfang_Cleaver.png", "Nightpiercer_Katana.png", "Ravenclaw_Cleaver.png",
    "Rotbone_Cleaver.png", "Storm_Amethyst_Fang.png", "Thornspire_Dirk.png",
    "Verdant_Fang_Cleaver.png", "Verdant_Scourge.png",
  ],
  scrolls: [
    "Azurite_Codex_of_Ruin.png", "Codex_of_Wasting.png", "Crimson_Binding_Scroll.png",
    "Cursed_Veilbound_Grimoire.png", "Forsaken_Veilbound_Codex.png", "Nightbound_Codex.png",
    "Paw_of_the_Covenant.png", "Scroll_of_Twilight_Ruin.png",
    "Scrolls_of_the_Starfall_Covenant.png", "Shattered_Codex_of_Withering_Truths.png",
    "Shattered_Embercall_Grimoire.png", "Storm_Crimson_Covenant_Scroll_3.png",
    "Storm_Veilscript_Codex.png", "Veilmark_Codex.png", "Veilweave_Codex.png",
    "Verdant_Blight_Codex.png", "Verdant_Grimoire_of_Blight.png",
    "Voidborn_Abyssal_Codex_Scroll.png", "Voidborn_Crimson_Covenant_Scroll.png",
    "Voidpact_Grimoire.png",
  ],
  bows: [
    "Ancient_Emberflight_Longbow.png", "Ancient_Thornwood_Whisper.png",
    "Carrionfeather_Longbow.png", "Cursed_Ebonwing_Recurve.png", "Ebonwhisper_Longbow.png",
    "Ebonwing_Recurve.png", "Ebonwood_Recurve.png", "Forsaken_Shadowpine_Recurve.png",
    "Frostbite_Whisper.png", "Hollow_Stormwrath_Recurve.png", "Ravenstrike_Longbow.png",
    "Scorchwing_Recurve.png", "Shadowpiercer_Longbow.png",
    "Shattered_Bloodthorn_Recurve.png", "Sorrow's_Crescent.png", "Spinebark_Recurve.png",
    "Spinethorn_Recurve.png", "Stormwrath_Recurve.png", "Voidborn_Shadowpine_Recurve.png",
    "Voidstrike_Recurve.png",
  ],
  staffs: [
    "Azureblight_Scepter.png", "Azurite_Thaumaturge's_Rod.png", "Bloodmoon_Scepter.png",
    "Bloodthorn_Scepter.png", "Bonegnaw_Crook.png", "Bonelust_Crook.png",
    "Bonewraith_Scepter.png", "Crescent_Voidstaff.png", "Crimson_Conduit_Staff.png",
    "Crimson_Thaumaturge's_Rod.png", "Ebonspire_Crook.png", "Embercrown_Staff.png",
    "Marrowveil_Scepter.png", "Ossein_Conduit_Staff.png", "Ossuary_Crook.png",
    "Serpent's_Coil_Staff.png", "Starfall_Scepter.png", "Stormveil_Scepter.png",
    "Thornwick_Conduit.png", "Verdant_Scepter_of_Thorns.png",
  ],
  helmets: [
    "Ancient_Grimscale_Helm.png", "Ancient_Grimscale_Helm_3.png", "Crimson_Ossuary_Crown.png",
    "Crimson_Thane_Helm.png", "Crimson_Thrall_Helm.png", "Crimson_Witch's_Helm.png",
    "Cursed_Grimscale_Coronet.png", "Emberveil_Coronet.png", "Emberveil_Crown.png",
    "Emberveil_Horns.png", "Forsaken_Emberveil_Crown.png", "Grimfeather_Helm.png",
    "Grimveil_Coronet.png", "Hollow_Grimscale_Helm.png", "Storm_Embercrest_Helm.png",
    "Thornscale_Helm.png", "Thornwood_Crown.png", "Voidborn_Emberveil_Helm.png",
    "Voidborn_Grimscale_Helm_4.png", "Voidwraith_Helm.png",
  ],
  plates: [
    "Azuremantle_Cuirass.png", "Bloodplate_Cuirass.png", "Bloodrite_Cuirass.png",
    "Bloodstitched_Doublet.png", "Bloodweave_Cuirass.png", "Bonelord's_Cuirass.png",
    "Crimson_Harbinger_Plate.png", "Crimson_Thornplate.png",
    "Cursed_Bloodweave_Cuirass_2.png", "Ember_Ironbound_Thoraxplate.png",
    "Goldenscale_Cuirass.png", "Goldplate_Sentinel.png", "Shadowplate_Corselet.png",
    "Shattered_Thornplate_Cuirass.png", "Thornbound_Cuirass.png", "Thornscale_Harness.png",
    "Thornweave_Cuirass.png", "Thornwood_Pauldrons.png", "Veilbound_Cuirass.png",
    "Voidborn_Goldenscale_Cuirass.png",
  ],
  mantles: [
    "Ancient_Shadowveil_Mantle.png", "Crimson_Veilcloak.png", "Duskweave_Mantle.png",
    "Ember_Ravenwing_Mantle.png", "Emberfell_Mantle.png", "Forsaken_Thornweave_Mantle.png",
    "Forsaken_Thornweave_Mantle_2.png", "Frostweave_Mantle.png", "Frostweaver's_Mantle.png",
    "Goldweave_Mantle.png", "Hollow_Shadowveil_Mantle.png", "Ravenwing_Shroud.png",
    "Shadowpall_Mantle.png", "Shattered_Frostweave_Mantle.png",
    "Shattered_Shadowveil_Mantle_2.png", "Shroudweaver's_Mantle.png",
    "Storm_Thornweave_Mantle.png", "Thornwood_Shroud.png",
    "Voidborn_Shadowveil_Mantle.png", "Voidborn_Shadowweave_Mantle_3.png",
  ],
  gloves: [
    "Ancient_Bloodwraith_Grips_2.png", "Bloodhound's_Grasp.png", "Bloodhusk_Grips.png",
    "Bloodpulse_Wraps.png", "Bloodsoaked_Wraiths.png", "Bloodthorn_Gauntlets.png",
    "Bloodveil_Gauntlets.png", "Bloodveil_Wraps.png", "Bloodweave_Grips.png",
    "Bloodwraith_Grips.png", "Cursed_Bonegrip_Gauntlets.png", "Ember_Ashen_Grips.png",
    "Hollow_Crimson_Thorngrips.png", "Nightfall_Grips.png", "Rotwood_Gauntlets.png",
    "Shadowpact_Grips.png", "Shadowveil_Grips.png", "Shattered_Veilweaver's_Grasp.png",
    "Veilwraith_Grips.png", "Wraithbound_Gauntlets.png",
  ],
  belts: [
    "Abyssal_Cinch.png", "Ancient_Cinderbound_Girdle_2.png", "Ancient_Wraithbound_Girdle.png",
    "Bloodwarden's_Cincture.png", "Bloodwrath_Girdle.png", "Boneweave_Girdle.png",
    "Carrionwraith_Girdle.png", "Crimson_Warden's_Girdle.png",
    "Cursed_Shadowbound_Girdle.png", "Ember_Cinderbound_Girdle.png",
    "Forsaken_Cinderbound_Girdle.png", "Hollow_Cinderbound_Girdle.png",
    "Shadowbind_Cincture.png", "Shadowbound_Girdle.png", "Storm_Abyssal_Cinch.png",
    "Storm_Cinderbound_Girdle.png", "Tarnished_Corslet_Girdle.png",
    "Verdant_Girdle_of_Thorns.png", "Verdant_Siege_Girdle.png", "Voidstitched_Girdle.png",
  ],
  boots: [
    "Amethyst_Marrow_Treads.png", "Ancient_Abyssal_Treads.png", "Ashenmire_Treads.png",
    "Ashenworn_Greaves.png", "Bloodmire_Treads.png", "Cindercrust_Greaves.png",
    "Cinderfell_Treads.png", "Crimson_Void_Treads.png", "Hollow_Frostbind_Treads.png",
    "Marrowstep_Treads.png", "Mossgrown_Treads.png", "Shadowstep_Greaves.png",
    "Shattered_Shadowstep_Greaves.png", "Stonewraith_Treads.png",
    "Storm_Mossgrown_Treads.png", "Stormveil_Treads.png", "Thornveil_Treads.png",
    "Umbralshard_Treads.png", "Voidborn_Embercinder_Treads.png",
    "Voidborn_Shadowstep_Greaves.png",
  ],
  rings: [
    "Ashborn_Signet.png", "Embercrest_Sigil.png", "Emberfang_Sigil.png",
    "Emberwraith_Sigil.png", "Forsaken_Abyssal_Signet.png",
    "Forsaken_Obsidian_Covenant_Ring.png", "Grimwood_Sigil.png", "Nightfall_Signet.png",
    "Oathkeeper's_Seal.png", "Obsidian_Covenant_Ring.png", "Ravenclaw_Sigil.png",
    "Sable_Oath_Sigil.png", "Serpent's_Covenant_Ring.png",
    "Shattered_Embercrest_Sigil.png", "Sigil_of_the_Withered_Crown.png",
    "Sovereign's_Seal.png", "Stormveil_Sigil.png", "Thornweave_Signet.png",
    "Voidborn_Serpent's_Coil_Ring_2.png", "Voidpulse_Sigil.png",
  ],
  amulets: [
    "Abyssal_Anchor.png", "Abyssal_Sigil.png", "Azurite_Watcher's_Seal.png",
    "Bloodwood_Effigy.png", "Chalice_of_Cinders.png", "Crimson_Oath_Medallion.png",
    "Crimson_Tether_Amulet.png", "Embercrest_Amulet.png", "Emberfang_Talisman.png",
    "Emberscourge_Talisman.png", "Gilded_Redemption_Cross.png", "Hollowveil_Talisman.png",
    "Latticebound_Talisman.png", "Luneblight_Charm.png", "Pawbound_Talisman.png",
    "Raven's_Hollow_Eye.png", "Shadowpact_Talisman.png", "Solaris_Oath_Amulet.png",
    "Verdant_Sorrow_Pendant.png", "Verdant_Teardrop_Amulet.png",
  ],
};

// ── Deterministic hash for per-icon stat pools ──────────

/** Simple string hash (djb2). Returns a positive integer. */
function hashStr(s: string): number {
  let h = 5381;
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  }
  return h;
}

/** Number of stats each individual item gets in its personal pool. */
const ITEM_POOL_SIZE = 5;

/**
 * Get a deterministic personal stat pool for a specific icon filename.
 * Uses the filename as a seed to always pick the same subset of stats.
 *
 * @param iconFilename - e.g. "Ashborn_Katana.png"
 * @param slotPool     - full stat pool for this slot (from SLOT_STAT_POOLS)
 * @returns subset of slotPool, always the same for the same filename
 */
export function getItemStatPool(iconFilename: string, slotPool: readonly string[]): string[] {
  if (slotPool.length <= ITEM_POOL_SIZE) return [...slotPool];

  const baseName = iconFilename.replace(/\.png$/i, '');
  const seed = hashStr(baseName);

  // Fisher-Yates shuffle with deterministic seed
  const pool = [...slotPool];
  let s = seed;
  for (let i = pool.length - 1; i > 0; i--) {
    // Simple LCG step for deterministic pseudo-random
    s = (s * 1664525 + 1013904223) >>> 0;
    const j = s % (i + 1);
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, ITEM_POOL_SIZE);
}

/**
 * Get deterministic stat range multipliers for a specific item.
 * Half of the item's stats get x2 ranges (strong stats), the other half get x0.5 (weak stats).
 * Uses filename hash with a different offset to produce a unique distribution per item.
 *
 * @param iconFilename - e.g. "Ashborn_Katana.png"
 * @param statPool     - the item's personal stat pool (from getItemStatPool)
 * @returns Record mapping each StatId to its multiplier (2.0 or 0.5)
 */
export function getItemStatMultipliers(iconFilename: string, statPool: readonly string[]): Record<string, number> {
  const baseName = iconFilename.replace(/\.png$/i, '');
  // Use a different seed offset so multiplier order differs from pool selection order
  const seed = hashStr(baseName + '_multipliers');

  // Shuffle indices to decide which stats get x2 vs x0.5
  const indices = statPool.map((_, i) => i);
  let s = seed;
  for (let i = indices.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) >>> 0;
    const j = s % (i + 1);
    [indices[i], indices[j]] = [indices[j], indices[i]];
  }

  // First half (floor) get x2, rest get x0.5
  const strongCount = Math.floor(statPool.length / 2);
  const result: Record<string, number> = {};
  for (let i = 0; i < indices.length; i++) {
    const statId = statPool[indices[i]];
    result[statId] = i < strongCount ? 2.0 : 0.5;
  }
  return result;
}

/**
 * Convert icon filename to display name.
 * "Ashborn_Katana.png" → "Ashborn Katana"
 * "Hollow_Emberfang_Cleaver_2.png" → "Hollow Emberfang Cleaver"
 */
export function iconToDisplayName(iconFilename: string): string {
  return iconFilename
    .replace(/\.png$/i, '')
    .replace(/_\d+$/, '')       // remove trailing _2, _3 etc.
    .replace(/_/g, ' ')
    .replace(/'/g, "'");
}

/**
 * Pick a random in-use icon path for the given equipment subtype code.
 * Returns { path, filename } so the caller can derive name and stat pool.
 */
export function pickRandomInUseIcon(subtypeCode: string): { path: string; filename: string } {
  const setKey = SUBTYPE_ICON_SET[subtypeCode];
  if (!setKey) return { path: "/assets/equipments/weapon/swords/in_use/Ashborn_Katana.png", filename: "Ashborn_Katana.png" };
  const folder = ICON_PATHS[setKey];
  const files = IN_USE_ICONS[setKey];
  if (!files || files.length === 0) return { path: folder + "/in_use/placeholder.png", filename: "placeholder.png" };
  const idx = Math.floor(Math.random() * files.length);
  const filename = files[idx];
  return { path: folder + "/in_use/" + filename, filename };
}

/**
 * Pick a random icon path for the given equipment subtype code.
 * Returns a full asset path like /assets/equipments/weapon/swords/Ashborn_Katana.png
 * @deprecated Use pickRandomInUseIcon instead for per-item stat pools and names
 */
export function pickRandomIcon(subtypeCode: string): string {
  const setKey = SUBTYPE_ICON_SET[subtypeCode];
  if (!setKey) return "/assets/equipments/weapon/swords/Ashborn_Katana.png";
  const folder = ICON_PATHS[setKey];
  const files = ICON_FILES[setKey];
  if (!files || files.length === 0) return folder + "/placeholder.png";
  const idx = Math.floor(Math.random() * files.length);
  return folder + "/" + files[idx];
}
