/**
 * Build-time script: generates the skill tree once and writes it as a static TypeScript file.
 *
 * Usage:  npx tsx shared/generate-tree.ts   (from project root)
 *
 * Output: shared/skill-tree-data.ts — pre-computed nodes, edges, emblems,
 *         figureEdgeSet, and figureMembership as plain data constants.
 */

/* eslint-disable no-console */

import * as fs from "fs";
import * as path from "path";

// Ensure skill-tree-data.ts exists (even if empty) before importing skill-tree.ts,
// because skill-tree.ts has a static import of skill-tree-data.ts.
const dataPath = path.resolve(__dirname, "skill-tree-data.ts");
if (!fs.existsSync(dataPath)) {
  fs.writeFileSync(dataPath, `
export const TREE_NODES: any[] = [];
export const TREE_EDGES: [number, number][] = [];
export const TREE_EMBLEMS: any[] = [];
export const TREE_FIGURE_EDGES: string[] = [];
export const TREE_FIGURE_MEMBERSHIP: [number, number][] = [];
`, "utf-8");
  console.log("Created stub skill-tree-data.ts for first generation");
}

async function main() {
  // Dynamic import — after stub file is in place
  const { generateSkillTree } = await import("./skill-tree");
  const { StatModifier } = await import("./skill-node-defs");

  const tree = generateSkillTree();

  // ── Serialize ──────────────────────────────────────────

  const serializedNodes = tree.nodes.map((n: any) => ({
    id: n.id,
    nodeId: n.nodeId,
    type: n.type,
    classAffinity: n.classAffinity,
    x: Math.round(n.x * 100) / 100,
    y: Math.round(n.y * 100) / 100,
    label: n.label,
    name: n.name,
    stat: n.stat,
    value: n.value,
    defId: n.def ? n.def.id : null,
    mods: n.mods.map((m: InstanceType<typeof StatModifier>) => ({
      stat: m.stat, value: m.value, mode: m.mode,
    })),
    connections: n.connections,
  }));

  const serializedEdges = tree.edges;
  const serializedEmblems = tree.emblems;
  const serializedFigureEdges = [...tree.figureEdgeSet];
  const serializedFigureMembership = [...tree.figureMembership.entries()];

  // ── Write TypeScript file ──────────────────────────────

  const output = `/**
 * Pre-computed skill tree data — generated by generate-tree.ts
 *
 * DO NOT EDIT MANUALLY. Regenerate: npx tsx shared/generate-tree.ts
 *
 * Generated: ${new Date().toISOString()}
 * Nodes: ${serializedNodes.length}
 * Edges: ${serializedEdges.length}
 */

/* eslint-disable */

export interface RawNode {
  id: number;
  nodeId: string;
  type: string;
  classAffinity: string;
  x: number;
  y: number;
  label: string;
  name: string | null;
  stat: string | null;
  value: number;
  defId: string | null;
  mods: { stat: string; value: number; mode: string }[];
  connections: number[];
}

export const TREE_NODES: RawNode[] = ${JSON.stringify(serializedNodes)};

export const TREE_EDGES: [number, number][] = ${JSON.stringify(serializedEdges)};

export const TREE_EMBLEMS: { classId: string; cx: number; cy: number; r: number; img: string; startNodeId: number }[] = ${JSON.stringify(serializedEmblems)};

export const TREE_FIGURE_EDGES: string[] = ${JSON.stringify(serializedFigureEdges)};

export const TREE_FIGURE_MEMBERSHIP: [number, number][] = ${JSON.stringify(serializedFigureMembership)};
`;

  fs.writeFileSync(dataPath, output, "utf-8");
  console.log(`Written ${dataPath}`);
  console.log(`  Nodes: ${serializedNodes.length}`);
  console.log(`  Edges: ${serializedEdges.length}`);
  console.log(`  Emblems: ${serializedEmblems.length}`);
  console.log(`  Figure edges: ${serializedFigureEdges.length}`);
  console.log(`  Figure membership entries: ${serializedFigureMembership.length}`);
}

main().catch(err => {
  console.error("Generation failed:", err);
  process.exit(1);
});
